const packageCopy = {
  hy: {
    eyebrow: 'ՄԵԿ ՓԱԹԵԹ · ՇԱՏ ՀԻՇՈՂՈՒԹՅՈՒՆՆԵՐ', title: 'Ձեր հաջորդ հանգիստը', subtitle: 'Ծովափ, նոր քաղաք կամ երկար սպասված ճամփորդություն։ Ընտրեք ուղղությունը, իսկ մանրամասները հավաքենք միասին։',
    destinations: 'Ո՞ւր եք ուզում մեկնել', allDestinations: 'Բոլոր ուղղությունները', providers: 'Մատակարարի նախընտրություն', allProviders: 'Ցանկացած մատակարար', providerNote: 'Մատակարարի ընտրությունը ձեր նախընտրությունն է։ Առաջարկն ու հասանելիությունը հաստատում է մեր մասնագետը։',
    departureFrom: 'Մեկնում՝ սկսած', departureTo: 'Մեկնում՝ մինչև', nightsMin: 'Գիշերներ՝ նվազագույն', nightsMax: 'Գիշերներ՝ առավելագույն', nights: 'գիշեր', anyMeal: 'Ցանկացած սնունդ', meal: 'Սնունդ', hotelStars: 'Հյուրանոցի կարգ', anyStars: 'Ցանկացած կարգ', budget: 'Գնի առավելագույն շեմ', budgetHint: 'Գնի շեմը վերաբերում է քարտում նշված գնին և արժույթին։',
    published: 'Առաջարկներ ձեր հանգստի համար', count: 'առաջարկ', manualNote: 'Գինը վերաբերում է քարտում նշված ամսաթվին և ուղևորների կազմին։ Վերջնական հասանելիությունը հաստատվում է հարցմամբ։',
    total: 'Ամբողջ խմբի համար', perPerson: 'Մեկ մեծահասակի համար', indicative: 'Խմբի նախնական արժեք', onRequest: 'Գինը՝ հարցմամբ', adults: 'մեծահասակ', children: 'երեխա', childAges: 'Երեխաների տարիքներ',
    includes: 'Ներառված է', excludes: 'Առանձին վճարվող ծառայություններ', terms: 'Հաստատման և չեղարկման պայմաններ', needsConfirmation: 'Մանրամասները հաստատվում են մասնագետի հետ', until: 'Առաջարկը գործում է մինչև', checked: 'Գինը ստուգված է', room: 'Սենյակ', source: 'Առաջարկի աղբյուր', operator: 'Տուրօպերատոր', fuel: 'Վառելիքի հավելավճար՝ ըստ մատակարարի',
    details: 'Դիտել փաթեթը', request: 'Հայտ ուղարկել', close: 'Փակել փաթեթը', noOffers: 'Գտնենք ձեր տարբերակը միասին', emptyText: 'Այս պայմաններով հրապարակված առաջարկ դեռ չկա։ Ուղարկեք ցանկությունները, և մասնագետը կստուգի համապատասխան փաթեթները։', custom: 'Անհատական փաթեթ', customText: 'Ունե՞ք այլ ուղղություն կամ հատուկ ցանկություն։ Նշեք դրանք հայտում։', catalogue: 'Դիտել նաև արտաքին տուրերը',
    live: 'Մատակարարի որոնման արդյունքներ', liveLoading: 'Ստուգում ենք առաջարկները…', livePartial: 'Ցուցադրված են այս պահին գտնված տարբերակները։', liveUnavailable: 'Առցանց առաջարկները հիմա հասանելի չեն։ Կարող եք ուղարկել հայտ՝ մասնագետի ստուգման համար։', liveRequirements: 'Առցանց որոնման համար նշեք Երևան (EVN), ուղղությունը և մեկնման մինչև 21-օրյա միջակայքը։ Առավելագույնը՝ 6 մեծահասակ և 3 երեխա։', livePricing: 'Նախնական գին․ վերջնական գումարը, հավելավճարներն ու ներառումները հաստատվում են առանձին։', noMapping: 'Այս ուղղության առաջարկները կստուգի մասնագետը։', direct: 'Միայն ուղիղ թռիչք · առցանց որոնում', liveAction: 'Ստուգել նաև առցանց',
    changed: 'Փոփոխել եք որոնման պայմանները։ Սեղմեք «Որոնել»՝ արդյունքները թարմացնելու համար։', error: 'Չհաջողվեց բեռնել առաջարկները։ Փորձեք կրկին։', retry: 'Կրկին փորձել', expired: 'Այս առաջարկն այլևս հասանելի չէ։ Թարմացրեք որոնումը։', selectedNote: 'Հայտը կուղարկվի ընտրված փաթեթի ամսաթվով և ուղևորների կազմով։ Այլ ցանկությունները նշեք հաղորդագրությունում։',
    meals: {RO:'Առանց սննդի', BB:'Նախաճաշ', HB:'Կիսապանսիոն', FB:'Լրիվ պանսիոն', AI:'All inclusive', UAI:'Ultra all inclusive'},
    inclusions: {flight:'Երկկողմանի թռիչք', baggage:'Ուղեբեռ', hotel:'Հյուրանոց', meals:'Սնունդ', transfer:'Տրանսֆեր', insurance:'Ապահովագրություն', taxes:'Հարկեր և վճարներ'},
  },
  ru: {
    eyebrow: 'ОДИН ПАКЕТ · МНОГО ВПЕЧАТЛЕНИЙ', title: 'Ваш следующий отпуск', subtitle: 'Море, новый город или долгожданное путешествие. Выберите направление — детали соберём вместе.',
    destinations:'Куда вы хотите поехать', allDestinations:'Все направления', providers:'Предпочтительный поставщик', allProviders:'Любой поставщик', providerNote:'Выбор поставщика — ваше пожелание. Предложение и наличие подтверждает наш специалист.',
    departureFrom:'Вылет начиная с', departureTo:'Вылет до', nightsMin:'Ночей от', nightsMax:'Ночей до', nights:'ночей', anyMeal:'Любое питание', meal:'Питание', hotelStars:'Категория отеля', anyStars:'Любая категория', budget:'Максимальная цена', budgetHint:'Лимит относится к цене и валюте, указанным в карточке.',
    published:'Предложения для вашего отдыха', count:'предложений', manualNote:'Цена относится к указанным датам и составу путешественников. Наличие подтверждается по запросу.',
    total:'За всю группу', perPerson:'За одного взрослого', indicative:'Предварительная цена за группу', onRequest:'Цена по запросу', adults:'взрослых', children:'детей', childAges:'Возраст детей',
    includes:'Включено', excludes:'Оплачивается отдельно', terms:'Условия подтверждения и отмены', needsConfirmation:'Детали уточняются со специалистом', until:'Предложение действует до', checked:'Цена проверена', room:'Номер', source:'Источник предложения', operator:'Туроператор', fuel:'Топливный сбор по данным поставщика',
    details:'Посмотреть пакет', request:'Отправить заявку', close:'Закрыть пакет', noOffers:'Найдём ваш вариант вместе', emptyText:'Опубликованных предложений по этим условиям пока нет. Отправьте пожелания — специалист проверит подходящие пакеты.', custom:'Индивидуальный пакет', customText:'Другое направление или особые пожелания? Укажите их в заявке.', catalogue:'Также посмотреть зарубежные туры',
    live:'Результаты поиска поставщика', liveLoading:'Проверяем предложения…', livePartial:'Показаны найденные к этому моменту варианты.', liveUnavailable:'Онлайн-предложения сейчас недоступны. Отправьте заявку для проверки специалистом.', liveRequirements:'Для онлайн-поиска укажите Ереван (EVN), направление и период вылета до 21 дня. Не более 6 взрослых и 3 детей.', livePricing:'Предварительная цена: итоговая сумма, доплаты и состав пакета подтверждаются отдельно.', noMapping:'Предложения по этому направлению проверит специалист.', direct:'Только прямой рейс · онлайн-поиск', liveAction:'Проверить также онлайн',
    changed:'Условия изменились. Нажмите «Поиск», чтобы обновить результаты.', error:'Не удалось загрузить предложения. Попробуйте ещё раз.', retry:'Повторить', expired:'Предложение больше недоступно. Обновите поиск.', selectedNote:'Заявка отправится с датами и составом путешественников выбранного пакета. Другие пожелания укажите в сообщении.',
    meals:{RO:'Без питания',BB:'Завтрак',HB:'Полупансион',FB:'Полный пансион',AI:'Всё включено',UAI:'Ультра всё включено'},
    inclusions:{flight:'Перелёт туда и обратно',baggage:'Багаж',hotel:'Отель',meals:'Питание',transfer:'Трансфер',insurance:'Страховка',taxes:'Налоги и сборы'},
  },
  en: {
    eyebrow:'ONE PACKAGE · SO MANY MEMORIES', title:'Your next escape', subtitle:'A beach, a new city or a long-awaited journey. Choose the destination, and let’s bring the details together.',
    destinations:'Where would you like to go', allDestinations:'All destinations', providers:'Preferred supplier', allProviders:'Any supplier', providerNote:'Your supplier choice is a preference. Our specialist will confirm the offer and availability.',
    departureFrom:'Depart from', departureTo:'Depart by', nightsMin:'Minimum nights', nightsMax:'Maximum nights', nights:'nights', anyMeal:'Any meal plan', meal:'Meal plan', hotelStars:'Hotel category', anyStars:'Any category', budget:'Maximum listed price', budgetHint:'The limit applies to the price basis and currency shown on each card.',
    published:'Offers for your next escape', count:'offers', manualNote:'Prices apply to the dates and travellers shown. Final availability is confirmed on request.',
    total:'For the whole party', perPerson:'Per adult', indicative:'Indicative party price', onRequest:'Price on request', adults:'adults', children:'children', childAges:'Children’s ages',
    includes:'Included', excludes:'Payable separately', terms:'Confirmation and cancellation terms', needsConfirmation:'Details to be confirmed with your specialist', until:'Offer valid until', checked:'Price checked', room:'Room', source:'Offer source', operator:'Tour operator', fuel:'Fuel supplement reported by supplier',
    details:'Explore package', request:'Send a request', close:'Close package', noOffers:'Let’s find your escape together', emptyText:'There are no published offers matching these preferences yet. Send your wishes and our specialist will check suitable packages.', custom:'A package made for you', customText:'Another destination or something special in mind? Include it in your request.', catalogue:'Explore international tours too',
    live:'Supplier search results', liveLoading:'Checking offers…', livePartial:'Showing the options found so far.', liveUnavailable:'Online offers are currently unavailable. Send a request for a specialist to check.', liveRequirements:'For online search, choose Yerevan (EVN), a destination and a departure window of up to 21 days. Maximum 6 adults and 3 children.', livePricing:'Indicative prices: final totals, supplements and inclusions are confirmed separately.', noMapping:'A specialist will check offers for this destination.', direct:'Direct flights only · online search', liveAction:'Also check online',
    changed:'You changed the search preferences. Select Search to update the results.', error:'We could not load the offers. Please try again.', retry:'Try again', expired:'This offer is no longer available. Refresh your search.', selectedNote:'Your request will use the dates and travellers in this package. Include other preferences in the message.',
    meals:{RO:'Room only',BB:'Breakfast',HB:'Half board',FB:'Full board',AI:'All inclusive',UAI:'Ultra all inclusive'},
    inclusions:{flight:'Return flight',baggage:'Baggage',hotel:'Hotel',meals:'Meals',transfer:'Transfer',insurance:'Insurance',taxes:'Taxes and fees'},
  },
}

export function usePackageText() {
  const { locale } = useLocale()
  return computed(() => packageCopy[locale.value as keyof typeof packageCopy] || packageCopy.en)
}
