const travelCopy = {
  hy: {
    travel: 'Պլանավորեք ձեր ճամփորդությունը', eyebrow: 'Ձեր հաջորդ պատմությունը', intro: 'Թռիչքից մինչև վերջին կանգառը՝ հավաքեք ձեր ճամփորդությունը մեկ տեղում։',
    services: { tours: 'Տուրեր', hotels: 'Հյուրանոցներ', flights: 'Ավիատոմսեր', cars: 'Մեքենաներ', transfers: 'Տրանսֆերներ', activities: 'Էքսկուրսիաներ', places: 'Տեսարժան վայրեր', packages: 'Տուրփաթեթներ' },
    descriptions: { tours: 'Բացահայտեք նոր երթուղիներ ու տեղական պատմություններ։', hotels: 'Քաղաքային հանգստից մինչև ծովափնյա առավոտներ։', flights: 'Ընտրեք ուղղությունը, մենք կօգնենք գտնել թռիչքը։', cars: 'Շարժվեք ձեր ռիթմով և ձեր ճանապարհով։', transfers: 'Հարմար ճանապարհ օդանավակայանից դեպի ձեր հանգիստը։', activities: 'Փոքր բացահայտումներ, մեծ հիշողություններ։', places: 'Գտեք վայրեր, որոնք կդառնան ձեր պատմության մասը։', packages: 'Թռիչք, կացարան և տրանսֆեր՝ մեկ ճամփորդության մեջ։' },
    search: 'Գտնել տարբերակներ', destination: 'Ո՞ւր եք գնում', origin: 'Որտեղի՞ց', airport: 'Օդանավակայանի կոդ (օր․ EVN)', date: 'Մեկնում', returnDate: 'Վերադարձ / դուրսգրում', time: 'Ժամանման ժամ', adults: 'Մեծահասակներ', children: 'Երեխաներ', age: 'Տարիքը', addChild: 'Ավելացնել երեխա', remove: 'Հեռացնել', rooms: 'Սենյակներ', cabin: 'Սպասարկման դաս', economy: 'Էկոնոմ', premium_economy: 'Պրեմիում էկոնոմ', business: 'Բիզնես', first: 'Առաջին', country: 'Բնակության երկիր (օր․ AM)', currency: 'Արժույթ',
    loading: 'Փնտրում ենք տարբերակներ…', searchError: 'Որոնումը չհաջողվեց։ Ստուգեք դաշտերը և փորձեք կրկին։', results: 'Ձեզ համար ընտրված տարբերակներ', noResults: 'Եկեք գտնենք հենց ձեր տարբերակը', noResultsText: 'Այս որոնման համար առցանց առաջարկ չկա։ Ուղարկեք հայտը՝ անհատական առաջարկ ստանալու համար։', request: 'Ստանալ անհատական առաջարկ', requestNote: 'Հայտը ամրագրում կամ վճարում չէ։ Գինն ու հասանելիությունը հաստատում ենք առանձին։', browse: 'Բացել բաժինը', details: 'Մանրամասներ', partner: 'Դիտել գործընկերոջ մոտ', from: 'Սկսած', total: 'Ընդհանուր', onRequest: 'Ըստ հարցման', previous: 'Նախորդ', next: 'Հաջորդ', unavailable: 'Այս աղբյուրի առաջարկներն այժմ հասանելի չեն։ Կարող եք ուղարկել անհատական հայտ։', locationRequired: 'Առցանց որոնման համար ընտրեք առաջարկվող քաղաքներից մեկը։ Մյուս ուղղությունների համար ուղարկեք հայտ։', sampleCities: 'Քաղաք կամ ուղղություն', pricing: 'Կատալոգի գները մեկնարկային են։ Գործընկերոջ մոտ վերջնական պայմանները կարող են փոխվել։',
    account: 'Իմ ճամփորդությունները', signIn: 'Մուտք գործել', register: 'Ստեղծել հաշիվ', signOut: 'Դուրս գալ', name: 'Անուն', email: 'Էլ․ փոստ', password: 'Գաղտնաբառ', confirmPassword: 'Կրկնել գաղտնաբառը', passwordHint: 'Առնվազն 10 նիշ՝ տառերով ու թվերով։', accountIntro: 'Պահեք ձեր հայտերը, դիտեք առաջարկները և հետևեք ճամփորդության նախապատրաստմանը։', accountError: 'Գործողությունը չհաջողվեց։ Ստուգեք տվյալները և փորձեք կրկին։', expired: 'Նիստն ավարտվել է։ Խնդրում ենք կրկին մուտք գործել։', noOrders: 'Ձեր հաջորդ ճամփորդությունը սկսվում է այստեղ', noOrdersText: 'Մուտք գործելուց հետո ուղարկված հայտերը կհայտնվեն այս բաժնում։ Նախկին հյուրային հայտերի համար կապվեք մեզ հետ՝ նշելով հայտի համարը։', accept: 'Համաձայն եմ առաջարկին', cancel: 'Չեղարկել հայտը', requestCancel: 'Խնդրել չեղարկում', acceptNote: 'Ձեր համաձայնությունից հետո մասնագետը կհաստատի հասանելիությունը։ Այս քայլով գումար չի գանձվում։', expires: 'Առաջարկն ուժի մեջ է մինչև', quoteExpired: 'Առաջարկի ժամկետն ավարտվել է։ Սպասեք նոր առաջարկի։', conditions: 'Առաջարկի պայմանները', history: 'Հայտի ընթացքը', refresh: 'Թարմացնել', confirmation: 'Հաստատման համար', tracking: 'Մուտք գործեք մինչև հայտը ուղարկելը՝ դրա ընթացքին հետևելու համար։', allServices: 'Բոլոր ծառայությունները', back: 'Վերադառնալ', updated: 'Փոփոխությունը պահպանվել է։',
    statuses: { new: 'Հայտն ընդունված է', reviewing: 'Մշակվում է', quoted: 'Առաջարկը պատրաստ է', accepted: 'Սպասում է հաստատման', confirmed: 'Հաստատված է', completed: 'Ավարտված է', cancelled: 'Չեղարկված է', cancellation_requested: 'Չեղարկումը քննարկվում է', pending: 'Սպասում է', failed: 'Պահանջում է մշակում' },
  },
  ru: {
    travel: 'Спланируйте своё путешествие', eyebrow: 'Ваша следующая история', intro: 'От перелёта до последней остановки — соберите путешествие в одном месте.',
    services: { tours: 'Туры', hotels: 'Отели', flights: 'Авиабилеты', cars: 'Автомобили', transfers: 'Трансферы', activities: 'Экскурсии', places: 'Достопримечательности', packages: 'Турпакеты' },
    descriptions: { tours: 'Новые маршруты и местные истории.', hotels: 'От городских выходных до утра у моря.', flights: 'Выберите направление — поможем найти перелёт.', cars: 'Путешествуйте в своём ритме.', transfers: 'Удобная дорога из аэропорта к месту отдыха.', activities: 'Маленькие открытия, большие воспоминания.', places: 'Места, которые станут частью вашей истории.', packages: 'Перелёт, проживание и трансфер в одной поездке.' },
    search: 'Найти варианты', destination: 'Куда', origin: 'Откуда', airport: 'Код аэропорта (например, EVN)', date: 'Отправление', returnDate: 'Возвращение / выезд', time: 'Время прибытия', adults: 'Взрослые', children: 'Дети', age: 'Возраст', addChild: 'Добавить ребёнка', remove: 'Удалить', rooms: 'Номера', cabin: 'Класс обслуживания', economy: 'Эконом', premium_economy: 'Премиум эконом', business: 'Бизнес', first: 'Первый', country: 'Страна проживания (например, AM)', currency: 'Валюта',
    loading: 'Ищем варианты…', searchError: 'Не удалось выполнить поиск. Проверьте поля и повторите попытку.', results: 'Варианты для вас', noResults: 'Давайте найдём ваш вариант', noResultsText: 'По этому запросу нет онлайн-предложений. Отправьте заявку для индивидуального подбора.', request: 'Получить предложение', requestNote: 'Заявка не является бронированием или оплатой. Цену и наличие подтверждаем отдельно.', browse: 'Открыть раздел', details: 'Подробнее', partner: 'Посмотреть у партнёра', from: 'От', total: 'Итого', onRequest: 'По запросу', previous: 'Назад', next: 'Далее', unavailable: 'Предложения этого поставщика сейчас недоступны. Вы можете отправить индивидуальную заявку.', locationRequired: 'Для онлайн-поиска выберите город из предложенных. Для других направлений отправьте заявку.', sampleCities: 'Город или направление', pricing: 'В каталоге указаны начальные цены. Окончательные условия у партнёра могут измениться.',
    account: 'Мои путешествия', signIn: 'Войти', register: 'Создать аккаунт', signOut: 'Выйти', name: 'Имя', email: 'Эл. почта', password: 'Пароль', confirmPassword: 'Повторите пароль', passwordHint: 'Не менее 10 символов, включая буквы и цифры.', accountIntro: 'Сохраняйте заявки, смотрите предложения и следите за подготовкой поездки.', accountError: 'Не удалось выполнить действие. Проверьте данные и повторите попытку.', expired: 'Сессия завершена. Войдите снова.', noOrders: 'Ваше следующее путешествие начинается здесь', noOrdersText: 'Заявки, отправленные после входа, появятся здесь. По прежним гостевым заявкам свяжитесь с нами и укажите номер заявки.', accept: 'Согласен с предложением', cancel: 'Отменить заявку', requestCancel: 'Запросить отмену', acceptNote: 'После вашего согласия специалист подтвердит наличие. На этом шаге оплата не взимается.', expires: 'Предложение действует до', quoteExpired: 'Срок предложения истёк. Ожидайте новое предложение.', conditions: 'Условия предложения', history: 'История заявки', refresh: 'Обновить', confirmation: 'Номер подтверждения', tracking: 'Войдите перед отправкой заявки, чтобы следить за её статусом.', allServices: 'Все услуги', back: 'Назад', updated: 'Изменение сохранено.',
    statuses: { new: 'Заявка получена', reviewing: 'В обработке', quoted: 'Предложение готово', accepted: 'Ожидает подтверждения', confirmed: 'Подтверждено', completed: 'Завершено', cancelled: 'Отменено', cancellation_requested: 'Отмена рассматривается', pending: 'Ожидание', failed: 'Требует внимания' },
  },
  en: {
    travel: 'Make room for your next journey', eyebrow: 'Your next story', intro: 'From the first flight to the last stop, bring your whole trip together in one place.',
    services: { tours: 'Tours', hotels: 'Hotels', flights: 'Flights', cars: 'Car rental', transfers: 'Transfers', activities: 'Experiences', places: 'Places to visit', packages: 'Travel packages' },
    descriptions: { tours: 'Discover new routes and local stories.', hotels: 'From city weekends to mornings by the sea.', flights: 'Choose a destination. We’ll help find your flight.', cars: 'Find your own pace and your own road.', transfers: 'An easy journey from the airport to your stay.', activities: 'Small discoveries. Lasting memories.', places: 'Find places that become part of your story.', packages: 'Flights, a stay and transfers in one journey.' },
    search: 'Find options', destination: 'Where to?', origin: 'Where from?', airport: 'Airport code (e.g. EVN)', date: 'Departure', returnDate: 'Return / check-out', time: 'Arrival time', adults: 'Adults', children: 'Children', age: 'Age', addChild: 'Add a child', remove: 'Remove', rooms: 'Rooms', cabin: 'Cabin class', economy: 'Economy', premium_economy: 'Premium economy', business: 'Business', first: 'First', country: 'Country of residence (e.g. AM)', currency: 'Currency',
    loading: 'Finding your options…', searchError: 'Search failed. Check the fields and try again.', results: 'Options for your journey', noResults: 'Let’s find your perfect fit', noResultsText: 'There are no online offers for this search. Send your request for a tailored proposal.', request: 'Request a proposal', requestNote: 'A request is not a booking or payment. We confirm pricing and availability separately.', browse: 'Explore', details: 'View details', partner: 'View with partner', from: 'From', total: 'Total', onRequest: 'On request', previous: 'Previous', next: 'Next', unavailable: 'This supplier’s offers are temporarily unavailable. You can still request a tailored proposal.', locationRequired: 'Choose a suggested city for online search. For other destinations, send a request.', sampleCities: 'City or destination', pricing: 'Catalogue prices are starting prices. Final partner prices and conditions may change.',
    account: 'My journeys', signIn: 'Sign in', register: 'Create an account', signOut: 'Sign out', name: 'Name', email: 'Email', password: 'Password', confirmPassword: 'Confirm password', passwordHint: 'At least 10 characters, including letters and numbers.', accountIntro: 'Keep your requests together, review proposals and follow your travel plans.', accountError: 'The action failed. Check your details and try again.', expired: 'Your session has expired. Please sign in again.', noOrders: 'Your next journey starts here', noOrdersText: 'Requests sent while signed in will appear here. For earlier guest requests, contact us with your request reference.', accept: 'Accept proposal', cancel: 'Cancel request', requestCancel: 'Request cancellation', acceptNote: 'After you accept, a specialist will confirm availability. No payment is taken at this step.', expires: 'Proposal valid until', quoteExpired: 'This proposal has expired. Please wait for an updated proposal.', conditions: 'Proposal conditions', history: 'Request history', refresh: 'Refresh', confirmation: 'Confirmation reference', tracking: 'Sign in before sending your request to follow its progress.', allServices: 'All services', back: 'Back', updated: 'Your change has been saved.',
    statuses: { new: 'Request received', reviewing: 'Under review', quoted: 'Proposal ready', accepted: 'Awaiting confirmation', confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', cancellation_requested: 'Cancellation under review', pending: 'Pending', failed: 'Needs attention' },
  },
}

export function useTravelText() {
  const { locale } = useLocale()
  return computed(() => travelCopy[locale.value as keyof typeof travelCopy] || travelCopy.en)
}
