<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { ArrowLeft, ArrowUpRight, CalendarDays, Download, FileUp, Loader2, Package, Plus, Save, X } from '@lucide/vue';
const props = defineProps({ api: { type: Function, required: true } });
const rows = ref(null), options = ref(null), selected = ref(null), language = ref('hy'), busy = ref(false), error = ref(''), notice = ref('');
const filters = reactive({search: '', provider: '', status: ''}), form = ref(null), importOpen = ref(false), importProvider = ref('local'), csv = ref(''), preview = ref(null);
const statuses = {draft: 'Սևագիր', published: 'Հրապարակված', archived: 'Արխիվացված'};
const inclusions = {flight:'Երկկողմանի թռիչք', baggage:'Ուղեբեռ', hotel:'Հյուրանոց', meals:'Սնունդ', transfer:'Տրանսֆեր', insurance:'Ապահովագրություն', taxes:'Հարկեր / վճարներ'};
const meals = {RO:'RO · Առանց սննդի', BB:'BB · Նախաճաշ', HB:'HB · Կիսապանսիոն', FB:'FB · Լրիվ պանսիոն', AI:'AI · All inclusive', UAI:'UAI · Ultra all inclusive'};
const providerNames = computed(() => ({local:'GoVista', ...Object.fromEntries((options.value?.providers || []).map(p => [p.code,p.name]))}));
const nowLocal = () => { const value = new Date(); value.setMinutes(value.getMinutes() - value.getTimezoneOffset()); return value.toISOString().slice(0,16); };
const localTime = value => { if (!value) return ''; const date = new Date(value); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0,16); };
const describeError = e => Object.values(e.response?.data?.errors || {}).flat().join(' ') || e.response?.data?.message || 'Գործողությունը չհաջողվեց։';
async function load(page = 1) { busy.value = true; error.value = ''; try { const {data} = await props.api.get('/admin/package-offers', {params: {...filters, page}}); rows.value = data; } catch(e) { error.value = describeError(e); } finally { busy.value = false; } }
onMounted(async () => { try { options.value = (await props.api.get('/v1/packages/options')).data; await load(); } catch(e) { error.value = describeError(e); } });
function create() {
  selected.value = null; error.value = ''; notice.value = ''; language.value = 'hy';
  form.value = {provider_code:'local', supplier_reference:'', title:{hy:'',ru:'',en:''}, description:{hy:'',ru:'',en:''}, terms:{hy:'',ru:'',en:''}, exclusions:{hy:'',ru:'',en:''}, destination_code:'sharm', origin:'EVN', hotel_name:'', stars:null, room_type:'', meal_plan:'AI', departure_date:'', nights:7, adults:2, children:[], inclusions:['hotel'], price:'', cost:'', currency:'AMD', price_basis:'party_total', image:'', status:'draft', availability:'on_request', valid_until:'', price_checked_at:'', internal_notes:''};
}
async function edit(id) {
  busy.value = true; error.value = ''; notice.value = '';
  try { const {data} = await props.api.get(`/admin/package-offers/${id}`); selected.value = id; language.value = 'hy'; form.value = {...data, departure_date: data.departure_date?.slice(0,10) || '', valid_until: localTime(data.valid_until), price_checked_at: localTime(data.price_checked_at), children:data.children || [], inclusions:data.inclusions || []}; for(const key of ['title','description','exclusions','terms']) form.value[key] = {hy:'',ru:'',en:'',...data[key]}; }
  catch(e) { error.value = describeError(e); } finally { busy.value = false; }
}
async function save() {
  if (busy.value) return; busy.value = true; error.value = ''; notice.value = '';
  const payload = JSON.parse(JSON.stringify(form.value));
  for (const key of ['price','cost','stars','departure_date','image','hotel_name','room_type']) if (payload[key] === '') payload[key] = null;
  for (const key of ['valid_until','price_checked_at']) payload[key] = payload[key] ? new Date(payload[key]).toISOString() : null;
  try { const {data} = selected.value ? await props.api.put(`/admin/package-offers/${selected.value}`, payload) : await props.api.post('/admin/package-offers', payload); selected.value = data.id; form.value.version = data.version; notice.value = data.status === 'published' ? 'Առաջարկը պահպանված է։ Հանրային ցուցադրումը կախված է ժամկետից և հասանելիությունից։' : 'Սևագիրը / արխիվը պահպանված է։'; }
  catch(e) { error.value = describeError(e); } finally { busy.value = false; }
}
async function upload(event) {
  const file = event.target.files?.[0]; if (!file) return;
  if(file.size > 5 * 1024 * 1024) { error.value = 'Ընտրեք մինչև 5 ՄԲ լուսանկար։'; return; }
  busy.value = true; error.value = ''; const body = new FormData(); body.append('file', file);
  try { const {data} = await props.api.post('/admin/upload', body); form.value.image = `/storage/${data.path}`; } catch(e) { error.value = describeError(e); } finally { busy.value = false; event.target.value = ''; }
}
async function template() { try { const {data} = await props.api.get('/admin/package-offers/template', {responseType:'blob'}); const url = URL.createObjectURL(new Blob(['\uFEFF',data],{type:'text/csv;charset=utf-8'})); const a = document.createElement('a'); a.href=url; a.download='govista-packages-template.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000); } catch(e) { error.value=describeError(e); } }
async function chooseCsv(event) { preview.value = null; error.value = ''; const file = event.target.files?.[0]; if (!file) return; if(file.size > 500000) {error.value='Ֆայլը պետք է լինի մինչև 500 ԿԲ։'; csv.value=''; return;} csv.value = await file.text(); }
async function previewCsv() { busy.value = true; error.value = ''; preview.value = null; try { preview.value = (await props.api.post('/admin/package-offers/import/preview', {provider_code:importProvider.value, csv:csv.value})).data; } catch(e) {error.value=describeError(e);} finally {busy.value=false;} }
async function commitCsv() { if(!preview.value?.token || busy.value) return; busy.value=true; error.value=''; try { const {data} = await props.api.post('/admin/package-offers/import/commit', {token:preview.value.token}); notice.value=`Ստեղծվել է ${data.created} սևագիր։ Ստուգեք գները, պայմաններն ու հրապարակումը։`; preview.value=null; csv.value=''; importOpen.value=false; await load(); } catch(e) {error.value=describeError(e);} finally {busy.value=false;} }
const expired = row => row.status === 'published' && (!row.valid_until || new Date(row.valid_until) <= new Date() || row.departure_date?.slice(0,10) < new Date().toLocaleDateString('en-CA'));
</script>
<template>
  <section class="platform-panel package-admin">
    <div class="platform-intro"><Package :size="30"/><div><h2>Պատրաստի տուրփաթեթներ</h2><p>Մատակարարի առաջարկից մինչև հրապարակում՝ մեկ տեղում։ Փաթեթի գինը, կազմը և պայմանները պահպանվում են հաճախորդի հայտի հետ։</p></div></div>
    <p v-if="error" role="alert" class="platform-error">{{ error }}</p><p v-if="notice" role="status" class="platform-success">{{ notice }}</p>
    <template v-if="!form">
      <div class="platform-actions"><button class="button button-primary" :disabled="busy || !options" @click="create"><Plus :size="16"/> Նոր փաթեթ</button><button class="button button-ghost" :disabled="busy" @click="importOpen=!importOpen; preview=null"><FileUp :size="16"/> Ներմուծել CSV-ից</button><a v-if="options?.public_url" class="button button-ghost" :href="options.public_url" target="_blank" rel="noopener noreferrer">Հանրային նախադիտում <ArrowUpRight :size="15"/></a></div>
      <section v-if="importOpen" class="package-import"><h3>Սկզբում ստուգում, հետո՝ ներմուծում</h3><p class="provider-footnote">UTF-8 CSV, մինչև 100 առաջարկ։ Ներմուծումը ստեղծում է միայն սևագրեր և չի վերագրում գործող առաջարկները։ Երեխաների տարիքներն ու ներառումները բաժանեք | նշանով։</p><button class="button button-ghost" @click="template"><Download :size="15"/> Ներբեռնել ձևանմուշը</button><label class="platform-field">Մատակարար<select v-model="importProvider" @change="preview=null"><option v-for="(name, code) in providerNames" :key="code" :value="code">{{name}}</option></select></label><label class="platform-field">CSV ֆայլ<input type="file" accept=".csv,text/csv" :disabled="busy" @change="chooseCsv"></label><button class="button button-primary" :disabled="busy || !csv" @click="previewCsv">Ստուգել և նախադիտել</button>
        <template v-if="preview"><p class="platform-note">Ճիշտ տողեր՝ {{preview.count}} · սխալներ՝ {{preview.errors.length}}։ Նախադիտումը գործում է 10 րոպե։</p><ul class="package-import-errors" v-if="preview.errors.length"><li v-for="issue in preview.errors" :key="issue.row">Տող {{issue.row}}՝ {{issue.messages.join(' ')}}</li></ul><div class="package-import-rows"><div v-for="row in preview.rows" :key="row.supplier_reference"><strong>{{row.supplier_reference}}</strong><span>{{row.title.hy}}</span><span>{{row.price || 'Գինը ճշտվում է'}} {{row.price ? row.currency : ''}}</span></div></div><button v-if="preview.token" class="button button-primary" :disabled="busy" @click="commitCsv">Ներմուծել {{preview.count}} սևագիր</button></template>
      </section>
      <form class="platform-filters" @submit.prevent="load()"><input v-model.trim="filters.search" aria-label="Փաթեթների որոնում" placeholder="Անվանում, հյուրանոց, մատակարարի համար" maxlength="120"><select v-model="filters.provider" aria-label="Մատակարարի ֆիլտր"><option value="">Բոլոր մատակարարները</option><option v-for="(name,code) in providerNames" :key="code" :value="code">{{name}}</option></select><select v-model="filters.status" aria-label="Հրապարակման կարգավիճակ"><option value="">Բոլոր վիճակները</option><option v-for="(label,key) in statuses" :key="key" :value="key">{{label}}</option></select><button class="button button-primary" :disabled="busy">Որոնել</button></form>
      <p v-if="busy" role="status" class="platform-note"><Loader2 :size="18" class="spin"/> Բեռնվում է…</p>
      <div v-if="rows?.data.length" class="platform-request-list"><button v-for="row in rows.data" :key="row.id" :disabled="busy" @click="edit(row.id)"><div><small>{{providerNames[row.provider_code]}} · {{row.supplier_reference}}</small><h3>{{row.title.hy}}</h3><p>{{row.origin}} → {{options?.destinations.find(d=>d.code===row.destination_code)?.names.hy}} · {{row.departure_date?.slice(0,10) || 'Ամսաթիվը նշված չէ'}} · {{row.nights}} գիշեր</p><p>{{row.price || 'Հարցմամբ'}} {{row.price ? row.currency : ''}} · {{row.price_basis==='party_total' ? 'ամբողջ խմբի համար' : 'մեկ անձի համար'}}</p></div><span class="status-chip">{{expired(row) ? 'Ժամկետանց · թաքցված' : row.availability==='sold_out' ? 'Վաճառված · թաքցված' : statuses[row.status]}}</span><ArrowUpRight :size="18"/></button></div>
      <div v-else-if="!busy" class="package-admin-empty"><Package :size="38"/><h3>Առաջարկներ դեռ չկան</h3><p>Ավելացրեք մատակարարից ստացված առաջին փաթեթը կամ ներմուծեք առաջարկների ֆայլը։</p></div>
      <div v-if="rows?.last_page>1" class="platform-actions"><button class="button button-ghost" :disabled="busy || rows.current_page<=1" @click="load(rows.current_page-1)">Նախորդ</button><span>{{rows.current_page}} / {{rows.last_page}}</span><button class="button button-ghost" :disabled="busy || rows.current_page>=rows.last_page" @click="load(rows.current_page+1)">Հաջորդ</button></div>
    </template>
    <form v-else class="package-editor" @submit.prevent="save">
      <div class="platform-actions"><button type="button" class="button button-ghost" :disabled="busy" @click="form=null; load()"><ArrowLeft :size="16"/> Փաթեթների ցանկ</button><span class="status-chip">{{selected ? `Առաջարկ #${selected}` : 'Նոր առաջարկ'}}</span></div>
      <div class="package-editor-grid"><section class="platform-editor"><h3>01 · Մատակարար և ուղղություն</h3><div class="platform-form-row"><label class="platform-field">Մատակարար<select v-model="form.provider_code"><option v-for="(name,code) in providerNames" :key="code" :value="code">{{name}}</option></select></label><label class="platform-field">Մատակարարի առաջարկի համար<input v-model.trim="form.supplier_reference" required maxlength="120"></label></div><div class="platform-form-row"><label class="platform-field">Ուղղություն<select v-model="form.destination_code"><option v-for="destination in options.destinations" :key="destination.code" :value="destination.code">{{destination.names.hy}}</option></select></label><label class="platform-field">Մեկնման օդանավակայան<input v-model.trim="form.origin" required pattern="[A-Z]{3}" maxlength="3" placeholder="EVN"></label></div><div class="language-tabs"><button v-for="code in ['hy','ru','en']" :key="code" type="button" :class="{active: language===code}" @click="language=code">{{code.toUpperCase()}}</button></div><label class="platform-field">Անվանում · {{language.toUpperCase()}}<input v-model="form.title[language]" :required="language==='hy'" maxlength="190"></label><label class="platform-field">Նկարագրություն · {{language.toUpperCase()}}<textarea v-model="form.description[language]" rows="4" maxlength="3000"></textarea></label><label class="platform-field">Ներառումներից դուրս · {{language.toUpperCase()}}<textarea v-model="form.exclusions[language]" rows="3" maxlength="2000" placeholder="Օրինակ՝ վիզա, անձնական ծախսեր"></textarea></label><label class="platform-field">Հաստատման / չեղարկման պայմաններ · {{language.toUpperCase()}}<textarea v-model="form.terms[language]" rows="4" maxlength="4000"></textarea></label><p class="provider-footnote">Չթարգմանված դաշտերի համար կցուցադրվի հայերեն տարբերակը։</p></section>
      <section class="platform-editor"><h3>02 · Ճամփորդության կազմը</h3><div class="platform-form-row"><label class="platform-field">Մեկնման ամսաթիվ<input v-model="form.departure_date" type="date"></label><label class="platform-field">Գիշերների քանակ<input v-model.number="form.nights" type="number" min="1" max="28" required></label></div><label class="platform-field">Հյուրանոց<input v-model="form.hotel_name" maxlength="190"></label><div class="platform-form-row"><label class="platform-field">Աստղեր<select v-model.number="form.stars"><option :value="null">Նշված չէ</option><option v-for="n in 5" :key="n" :value="n">{{n}} ★</option></select></label><label class="platform-field">Սնունդ<select v-model="form.meal_plan"><option v-for="(label,key) in meals" :key="key" :value="key">{{label}}</option></select></label></div><label class="platform-field">Սենյակի տեսակ<input v-model="form.room_type" maxlength="190"></label><label class="platform-field">Մեծահասակներ<input v-model.number="form.adults" required type="number" min="1" max="9"></label><div class="package-age-list"><label v-for="(_,index) in form.children" :key="index" class="platform-field">Երեխայի տարիք {{index+1}}<input v-model.number="form.children[index]" type="number" min="0" max="17" required><button type="button" :aria-label="`Հեռացնել երեխային ${index+1}`" @click="form.children.splice(index,1)"><X :size="14"/></button></label></div><button type="button" class="button button-ghost" :disabled="form.children.length>=6" @click="form.children.push(5)"><Plus :size="15"/> Ավելացնել երեխա</button><h4>Գնի մեջ ներառված է</h4><div class="package-inclusion-checks"><label v-for="(label,key) in inclusions" :key="key" class="platform-check"><input v-model="form.inclusions" type="checkbox" :value="key">{{label}}</label></div></section>
      <section class="platform-editor"><h3>03 · Գին և գործողության ժամկետ</h3><div class="platform-form-row"><label class="platform-field">Վաճառքի գին<input v-model="form.price" type="number" min="0.01" max="999999999.99" step="0.01" placeholder="Դատարկ՝ գինը հարցմամբ"></label><label class="platform-field">Արժույթ<select v-model="form.currency"><option v-for="code in ['AMD','USD','EUR','RUB','GBP','AED']" :key="code">{{code}}</option></select></label></div><label class="platform-field">Գինը վերաբերում է<select v-model="form.price_basis"><option value="party_total">Նշված ամբողջ խմբին</option><option value="per_person">Մեկ մեծահասակին՝ նշված տեղաբաշխմամբ</option></select></label><label class="platform-field">Ներքին ինքնարժեք<input v-model="form.cost" type="number" min="0" max="999999999.99" step="0.01"></label><p class="provider-footnote">Ինքնարժեքն ու ներքին նշումները հանրային կայքում չեն երևում։ Մեկ անձի գինը երեխաներով խմբի ընդհանուր գին չի հաշվարկում։</p><label class="platform-field">Գինը ստուգված է<input v-model="form.price_checked_at" type="datetime-local" :max="nowLocal()"></label><button type="button" class="button button-ghost" @click="form.price_checked_at=nowLocal()"><CalendarDays :size="15"/> Գինը ստուգեցի հիմա</button><label class="platform-field">Առաջարկը գործում է մինչև<input v-model="form.valid_until" type="datetime-local"></label><p class="provider-footnote">Ժամկետանց, անցած մեկնմամբ կամ 30 օրից ավելի հին գնով առաջարկները թաքցվում են։</p></section>
      <section class="platform-editor"><h3>04 · Լուսանկար և հրապարակում</h3><label class="platform-field">Լուսանկարի տեղական ուղի<input v-model="form.image" maxlength="500" placeholder="/storage/uploads/..."></label><label class="platform-field">Վերբեռնել լուսանկար<input type="file" accept="image/jpeg,image/png,image/webp" :disabled="busy" @change="upload"></label><p class="provider-footnote">Օգտագործեք հրապարակման իրավունք ունեցող լուսանկար։</p><div class="platform-form-row"><label class="platform-field">Հրապարակում<select v-model="form.status"><option v-for="(label,key) in statuses" :key="key" :value="key">{{label}}</option></select></label><label class="platform-field">Հասանելիություն<select v-model="form.availability"><option value="on_request">Հաստատվում է հարցմամբ</option><option value="sold_out">Վաճառված է / անհասանելի</option></select></label></div><label class="platform-field">Ներքին նշումներ<textarea v-model="form.internal_notes" maxlength="4000" rows="4"></textarea></label><p class="platform-note">Հրապարակման համար անհրաժեշտ են գործող ամսաթիվ, պայմաններ և մատակարարի հաստատված համագործակցություն։ Սա արտաքին ամրագրում կամ վճարում չի կատարում։</p></section></div>
      <div class="package-save-bar"><span>{{selected ? `Փոփոխություններ՝ #${selected}` : 'Պատրաստեք և ստուգեք առաջարկը'}}</span><button class="button button-primary" :disabled="busy"><Loader2 v-if="busy" class="spin" :size="17"/><Save v-else :size="17"/> Պահպանել առաջարկը</button></div>
    </form>
  </section>
</template>
